variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"
  BRANCH_NAME: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: pagopaEcommerceLocal
      type: github
      name: pagopa/pagopa-ecommerce-local
      ref: CHK-4375-add-cdc-tests
      endpoint: 'io-azure-devops-github-ro'

stages:
  - stage: BuildAndUnitTest
    displayName: 'Code Review'
    jobs:
      - job: make_buildAndUnitTest
        displayName: "Build and Test"
        steps:
          - task: Cache@2
            displayName: 'Configure Gradle caching'
            inputs:
              key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts' # Swap build.gradle.kts for build.gradle when using Groovy
              restoreKeys: |
                gradle | "$(Agent.OS)"
                gradle
              path: $(GRADLE_USER_HOME)

          - task: SonarCloudPrepare@3
            displayName: 'Prepare SonarCloud analysis'
            inputs:
              SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
              organization: '$(SONARCLOUD_ORG)'
              scannerMode: Other
              extraProperties: |
                sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
                sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
                sonar.coverage.exclusions=**/config/*,**/*Mock*,**/model/*
                sonar.coverage.jacoco.xmlReportPaths=./build/reports/jacoco/test/jacocoTestReport.xml
                sonar.junit.reportPaths=./build/test-results/test

          # install commons
          - task: Gradle@3
            displayName: 'Build and Install Commons Dependency'
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'install-commons -PbuildCommons'
              publishJUnitResults: false
              codeCoverageToolOption: 'None'
              sonarQubeRunAnalysis: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.21'

          # run the main build
          - task: Gradle@3
            displayName: 'Run Gradle build and tests'
            inputs:
              gradleWrapperFile: 'gradlew' # string. Alias: wrapperScript. Required. Gradle wrapper. Default: gradlew.
              tasks: 'build' # string. Required. Tasks. Default: build.
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml' # string. Required when publishJUnitResults = true. Test results files. Default: **/TEST-*.xml.
              codeCoverageToolOption: 'None' # 'None' | 'Cobertura' | 'JaCoCo'. Alias: codeCoverageTool. Code coverage tool. Default: None.
              codeCoverageClassFilesDirectories: 'build/classes/main/' # string. Alias: classFilesDirectories. Required when codeCoverageTool != None. Class files directories. Default: build/classes/main/.
              javaHomeOption: 'JDKVersion' # 'JDKVersion' | 'Path'. Alias: javaHomeSelection. Required. Set JAVA_HOME by. Default: JDKVersion.
              jdkVersionOption: '1.21' # 'default' | '1.11' | '1.10' | '1.9' | '1.8' | '1.7' | '1.6'. Alias: jdkVersion. Optional. Use when javaHomeSelection = JDKVersion. JDK version. Default: default.
              sonarQubeRunAnalysis: true

          - task: SonarCloudPublish@3
            displayName: 'Publish SonarCloud results on build summary'
            inputs:
              pollingTimeoutSec: '300'

          - script: |
              # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
              ./gradlew --stop
            displayName: 'Stop the Gradle daemon'

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish Code Coverage on Azure Devops'
            inputs:
              codeCoverageTool: 'JaCoCo'
              summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
              reportDirectory: 'build/reports/jacoco/test/html'

  - stage: IntegrationTestEcommerceLocal
    displayName: "Integration Tests"
    dependsOn: [ ]
    jobs:
      - job: make_IntegrationTestEcommerceLocal
        displayName: "Integration test using ecommerce-local environment"
        steps:
          - checkout: pagopaEcommerceLocal
          - script: |
              echo "##[debug] Change placeholder for ecommerce-cdc-service set branch: $(BRANCH_NAME)"
              sed -i "s/^ECOMMERCE_CDC_COMMIT_SHA=.*$/ECOMMERCE_CDC_COMMIT_SHA=$(BRANCH_NAME)/" .env
            displayName: 'Change ecommerce-cdc-service branch name ecommerce-local .env'
#          - script: |
#              # Create temporary override file for CDC test configuration
#              cat > docker-compose.cdc-override.yml << 'EOF'
#              services:
#                pagopa-ecommerce-transactions-service:
#                  environment:
#                    - TRANSACTIONSVIEW_UPDATE_ENABLED=false
#                pagopa-ecommerce-event-dispatcher-service:
#                  environment:
#                    - TRANSACTIONSVIEW_UPDATE_ENABLED=false
#              EOF
#              echo "Created CDC override file"
#            displayName: 'Create CDC test configuration override'
          - script: |
              TRANSACTIONSVIEW_UPDATE_ENABLED=false docker compose up \
              pagopa-ecommerce-cdc-service pagopa-ecommerce-transactions-service \
              pagopa-ecommerce-event-dispatcher-service pagopa-ecommerce-payment-methods-service \
              mongo mongo-init redis storage traefik pagopa-jwt-issuer-mock pagopa-node-mock pagopa-pdv-mock -d
            displayName: 'Start all services with CDC test configuration'
          - script: |
              echo "Verifying TRANSACTIONSVIEW_UPDATE_ENABLED environment variable override..."
              echo "Checking transactions-service container:"
              docker exec pagopa-ecommerce-transactions-service env | grep TRANSACTIONSVIEW_UPDATE_ENABLED || echo "TRANSACTIONSVIEW_UPDATE_ENABLED not found in transactions-service"
              echo "Checking event-dispatcher-service container:"
              docker exec pagopa-ecommerce-event-dispatcher-service env | grep TRANSACTIONSVIEW_UPDATE_ENABLED || echo "TRANSACTIONSVIEW_UPDATE_ENABLED not found in event-dispatcher-service"
              
              # Verify the setting is actually false for both services
              TRANS_VAR=$(docker exec pagopa-ecommerce-transactions-service env | grep TRANSACTIONSVIEW_UPDATE_ENABLED | cut -d'=' -f2)
              DISP_VAR=$(docker exec pagopa-ecommerce-event-dispatcher-service env | grep TRANSACTIONSVIEW_UPDATE_ENABLED | cut -d'=' -f2)
              
              if [[ "$TRANS_VAR" == "false" && "$DISP_VAR" == "false" ]]; then
                echo "✅ Environment variable override successful - both services have TRANSACTIONSVIEW_UPDATE_ENABLED=false"
              else
                echo "❌ Environment variable override failed:"
                echo "  transactions-service: TRANSACTIONSVIEW_UPDATE_ENABLED=$TRANS_VAR (expected: false)"
                echo "  event-dispatcher-service: TRANSACTIONSVIEW_UPDATE_ENABLED=$DISP_VAR (expected: false)"
                exit 1
              fi
            displayName: 'Verify CDC test isolation - environment variable override'
          - script: |
              timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8099/actuator/health/liveness)" != "200" ]]; do sleep 5; done' || exit 1
            displayName: 'Health check CDC service'
          - script: |
              timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/actuator/health/liveness)" != "200" ]]; do sleep 5; done' || exit 1
            displayName: 'Health check transactions service'  
          - script: |
              timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9000/actuator/health/liveness)" != "200" ]]; do sleep 5; done' || exit 1
            displayName: 'Health check event dispatcher service'
          - script: |
              timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8083/actuator/health/liveness)" != "200" ]]; do sleep 5; done' || exit 1
            displayName: 'Health check payment methods service'
          - script: yarn global add newman
            displayName: 'newman installation'
          - script: |
              newman run api-tests/cdc-service/cdc-service_ecommerce_local.postman_collection.json \
                --environment=api-tests/cdc-service/cdc-service_ecommerce_local.postman_environment.json \
                --reporters cli,junit \
                --reporter-junit-export Results/cdc-api-test.xml
            displayName: 'Run CDC Service API Tests'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/*-TEST.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)'
            displayName: 'Publish Integration Test Results'
